# Generated by Django 5.1.2 on 2024-10-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saccos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=50)),
                ('route_id', models.CharField(max_length=10)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IsaTest.saccos')),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('destination_id', models.CharField(max_length=10)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IsaTest.saccos')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=10)),
                ('condition', models.CharField(max_length=20, null=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IsaTest.saccos')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IsaTest.saccos')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IsaTest.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Conductors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IsaTest.saccos')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IsaTest.vehicles')),
            ],
        ),
    ]
