# Generated by Django 5.1.2 on 2024-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.FileField(null=True, upload_to='Profiles/'),
        ),
    ]
